### ISSUE TITLE
Need a way to set update frequency and/or check updates manually

### ISSUE THREAD

**Issue by YurySolovyov** [sindresorhus/notifier-for-github#11]
Otherwise it feels too unresponsive.

**Comment by gcochard** [comment]
I have a working branch with the Notifications API, utilizing the Last-Modified header. Would you like a PR?

**Comment by sindresorhus** [comment]
Yes, that would be appreciated :)

**Comment by gcochard** [comment]
We need to acquire an oauth token to use the notifications api. There are a few ways to do this:
1. The [web application flow](https://developer.github.com/v3/oauth/#web-application-flow)
2. The [non web application flow](https://developer.github.com/v3/oauth/#non-web-application-flow)
3. Have the user create one and copy/paste into the options

Thoughts on the preferred method? I currently use 3, but it should probably be automatic. I would prefer 1 due to the fact that we never touch the user's credentials.

**Comment by gcochard** [comment]
1 is out, we cannot store the client secret securely in the extension.

With 2, we will have to prompt the user for credentials once, then request and store a token.

**Comment by eprouty12** [comment]
3. seems best to me, especially dealing with enterprise github... not sure I'd always want to trust an open source project to have even temporary access to something that can create oauth tokens.

**Comment by gcochard** [comment]
I think 2 and 3 could be combined by asking for an OAuth token and describing how to create one, but also showing a "Please do this for me" button that prompts for credentials and exchanges them for a token via the API.

**Comment by sindresorhus** [comment]
I'm fine with either `3` or `2 and 3`. It's easy enough to link the user to the page to create a token though: https://github.com/settings/tokens/new

**Comment by gcochard** [comment]
I'll leave option 3 intact then. If there's enough noise from users, it can always be added later.

Currently working through some issues with the `Last-Modified` header, GitHub (Enterprise, at least) seems to always report 304.

PR will come as soon as that works properly.

**Comment by gcochard** [comment]
Okay, I figured it out.

> If there are no new notifications, you will see a “304 Not Modified” response...

So the issue is that I am marking notifications as read, and my count does not go down. There aren't any **new** notifications, therefore I get a `304` response. Until a *new* notification comes in, the count will always stay the same.

Additionally, when a new notification *does* come in, the `If-Modified-Since` header instructs GH to only retrieve notifications since then. Therefore I will only ever see the last minute worth of notification count.

Given that the old method broke with version 2.1 of GH:Enterprise, I will do the following:

- Abandon the `Last-Modified`/`If-Modified-Since` headers and affect the rate limit.
- File an issue with Github, hoping they will change the API semantics or add a route for notification count.

**Comment by eprouty** [comment]
Any updates on the pull that gcochard opened?  I'd really like to start using this extension with our enterprise github.
