### ISSUE TITLE
On FF 48+ the icon is displayed in the toolbar but clicking it does nothing 

### ISSUE THREAD

**Issue by xenithorb** [sindresorhus/notifier-for-github#127]
Title pretty much says it all. Just grab a copy of firefox, install it from chrome-store-foxified, and then play around with it.

**Comment by ExE-Boss** [comment]
This was caused by [line `67` in `main.js`](https://github.com/sindresorhus/notifier-for-github-chrome/blob/master/extension/main.js#L67) calling `PermissionsService.requestPermission('tabs')`, which is unsupported by Firefox, and throws a [`TypeError: window.chrome.permissions is undefined`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError).

The solution was implemented in [#128 – `PermissionsService`](https://github.com/sindresorhus/notifier-for-github-chrome/pull/128/files#diff-589c535d8b72b027f43ec4d763d04b7a).
