### ISSUE TITLE
Stops working in Firefox 57

### ISSUE THREAD

**Issue by sseppola** [sindresorhus/notifier-for-github#137]
Hi, this plugin stopped working when I upgraded to FF 57 as Firefox removed the legacy api (ref https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing)

I'm willing to have a go at fixing this myself if it's not already in progress. Let me know if this is desirable :)

**Comment by YurySolovyov** [comment]
Yup, PRs are welcome

**Comment by tooomm** [comment]
As written in https://github.com/sindresorhus/notifier-for-github/pull/140 there is no way to install on recent firefox versions yet since an official release at AMO is missing I think.

Installing via the "Chrome Store Foxified" extension as [described in the README](https://github.com/sindresorhus/notifier-for-github#install) doesn't really work, and one wouldn't get any updates...
