### ISSUE TITLE
Use `async/await`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/notifier-for-github#149]
Replace all the use of `.then()` with `await`.

Could also look into using other ES2015+ features.

**Comment by FadySamirSadek** [comment]
I will pick this one up

**Comment by FadySamirSadek** [comment]
@sindresorhus I have a question while implementing this task I used try, catch instead of .then , .catch to handle errors but some functions are calling the handleError function on catch and others do not have a catch statement.  

So my question is should I send all errors to the handle error function or this is not the intended behavior and we want to store some of these errors somewhere else instead of badging them to the user ?

**Comment by sindresorhus** [comment]
@FadySamirSadek Let's just go with what's already there, so if the error is not currently caught, don't, if it uses `handleError`, continue to use that.
