### ISSUE TITLE
Travis is failing

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/notifier-for-github#152]
https://travis-ci.org/sindresorhus/notifier-for-github/builds/395821875?utm_source=github_status&utm_medium=notification

@notlmn Could you take a look?

**Comment by notlmn** [comment]
@sindresorhus The problem is with the `chrome-stub` package having dependencies from 2013 that use legacy code which breaks in newer version of node.

`chrome-stub` has a dependency of `lodash@2.4.2`, which has [this line of code](https://github.com/lodash/lodash/blob/29a7bc4c817cbd87c8f5940fbeff32e879457b89/dist/lodash.js#L141), in which `this` refers to an empty object (because its inside a `function`), making [this line of code](https://github.com/lodash/lodash/blob/29a7bc4c817cbd87c8f5940fbeff32e879457b89/dist/lodash.js#L437) to not work as intended, and finally throwing on [this line](https://github.com/lodash/lodash/blob/29a7bc4c817cbd87c8f5940fbeff32e879457b89/dist/lodash.js#L460).

I opened an [issue](https://github.com/gcochard/chrome-stub/issues/9) on `chrome-stub` to tell them to update their dependencies (which fixed the tests). It also looks like `chrome-stub` hasn't been update since a while. So if they do not respond, then we may have to write some extra boilerplate code in `test/fixtures/globals.js` to fix this ourselves.

**Comment by notlmn** [comment]
Time taken to debug: 4 hours, because
* For some reason my apt installed `node@10.4.0` decided to pass the tests where others didn't.
* Don't know how to debug tests with debugger using `ava` (shouting out to Sindre). Been `console.log`ging all the way.
* I thought I may have found an issue with `nvm` installed and `apt` installed variants of `node`.

**Comment by sindresorhus** [comment]
Thanks for investigating. If the maintainer of `chrome-stub` doesn't respond, we can either fork and update the dependencies or switch to https://github.com/acvetkov/sinon-chrome

**Comment by sindresorhus** [comment]
@notlmn No response yet. Let's just fork `chrome-stub` and update its dependencies.

**Comment by notlmn** [comment]
As we are already using `sinon`, wouldn't it be better if we use `sinon-chrome` because it is updated frequently and we don't have to make a fork?

**Comment by sindresorhus** [comment]
Sure, that would probably be better.
