### ISSUE TITLE
Chrome 68 - Could not request notifications permission

### ISSUE THREAD

**Issue by ankurk91** [sindresorhus/notifier-for-github#156]
Hi,
Today i got an update and extension stopped working.
I removed and re-installed the extension but no luck.
See the GIF -

![notify-options](https://user-images.githubusercontent.com/6111524/43202731-dfc33424-9039-11e8-9bd7-282b8c186366.gif)

I tried restarting the browser but still same results.

* Extension version: 18.7.25.917
* Chrome version: Version 68.0.3440.75 (Official Build) (64-bit)
* OS: MacOS 10.12

What other information should i provide?

**Comment by crimx** [comment]
This is the related code. Use promise instead of callback.

https://github.com/sindresorhus/notifier-for-github/blob/5f6c1bcb810325c7f5dbd35d47045a5f25ee4ec6/source/lib/permissions-service.js#L3-L15

https://github.com/sindresorhus/notifier-for-github/blob/5f6c1bcb810325c7f5dbd35d47045a5f25ee4ec6/source/lib/permissions-service.js#L17-L32

**Comment by johnbellessa** [comment]
You might want to revoke the token visible in your gif

**Comment by ankurk91** [comment]
This the input field placeholder. Not the real token.

**Comment by johnbellessa** [comment]
Good deal, just looking out 🙂

**Comment by notlmn** [comment]
Closed in a04e891

@crimx I was expecting that the permissions API would bite us back at some point, and that is now!

**Comment by notlmn** [comment]
Closed in a04e891

@crimx I was expecting that the permissions API would bite us back at some point, and that is now!
