### ISSUE TITLE
Receiving stale notifications

### ISSUE THREAD

**Issue by RomanKornev** [sindresorhus/notifier-for-github#168]
When GitHub has multiple new notifications at the same time, notifier doesn't display them all. Only the first couple. 
Then if I view them in the browser and after 10 minutes a new one arrives, notifier will re-send previously read notifications from 10 minutes ago all at once.

**Comment by notlmn** [comment]
Are you on Windows? Because when we send multiple notifications, all at once, Windows seems to show only some of them, ignoring the others for some time. Windows' notifications system could use some improvements though 😁.

**Comment by RomanKornev** [comment]
> Are you on Windows? 

Windows 10 x64 1809.

Maybe instead of sending 3+ notifications at the same time, just send one "3 new notifications" or something?

**Comment by notlmn** [comment]
> Maybe instead of sending 3+ notifications at the same time, just send one "3 new notifications" or something?

I think that's a better way of handling notifications, like what Mail app does on Windows. But then on click we'd have to open that repos notifications page.

PRs welcome to modify the code, meanwhile I'll try working on it too.

**Comment by notlmn** [comment]
@romankornev are you still seeing this behavior?

Thinking again about this, it looks like showing something like "3 new notifications" is not an ideal solution, as users use the notification feature so that they do not have to go to the notifications page in the first place.

I'd like to close this issue if you are still experiencing this behavior, otherwise feel free to provide more info on how this affects you and any other possible solutions to improve this.
