### ISSUE TITLE
Jump to newest comment instead of just opening the issue

### ISSUE THREAD

**Issue by RomanKornev** [sindresorhus/notifier-for-github#169]
That's how GitHub opens notifications.
`USER/REPO/issues/ISSUE_ID#issuecomment-COMMENT_ID`

**Comment by notlmn** [comment]
GitHub by default links to the last comment that you missed. That's the link opened when a notification is clicked on.

What issue are you exactly experiencing? Is NGH always opening the URL and not the latest comment?

**Comment by RomanKornev** [comment]
> Is NGH always opening the URL and not the latest comment?

Yes, it just opens the top of the issue. It doesn't scroll to last comment, last comment isn't highlighted, link is missing `#issuecomment-COMMENT_ID`

**Comment by notlmn** [comment]
This is one of the neat features that I would want to have too, but sadly GitHub sends URL of notification without the fragment part 😕, possibly for compatibility with other applications.

![image](https://user-images.githubusercontent.com/37769974/52521551-bda9fd80-2c9e-11e9-853f-b5b1d193f9fd.png)

**Comment by RomanKornev** [comment]
How about using the Github API to get the latest comment?
For example this:
https://api.github.com/repos/sindresorhus/notifier-for-github/issues/169/comments
Latest comment entry returns:
```
html_url: "https://github.com/sindresorhus/notifier-for-github/issues/169#issuecomment-462045781"
```
Might even use https://api.github.com/repos/sindresorhus/notifier-for-github/issues/169/events as well for non-comment events.
Then merge `comments` and `events` and return whichever one is latest by `created_at` timestamp.
The problem is `latest` might not be the last unread.
Does the Github notifications page return the `latest` as well? I'm not sure.
Having more requests is not super critical, considering we only update once per minute at most.

**Comment by notlmn** [comment]
The actual problem is none of these solutions give you the __"last unread comment"__, they give you the __"last comment"__ or __"last event"__, but what we need is link to the last comment that user has read (which only comes through notifications).

We could still use the latest comment ID, but that would be equal as pressing <kbd>End</kbd> on page load (or using "Jump To Bottom" feature of [RGH](https://github.com/sindresorhus/refined-github)), which makes the additional requests not worth it.

🤷‍♂️

**Comment by RomanKornev** [comment]
We can use `last_read_at` timestamp of https://api.github.com/notifications?per_page=100 to figure out which events/comments are still unread (`created_at` field). Then construct the URL with `#issuecomment-COMMENT_ID` or `#event-EVENT_ID`.

>that would be equal as pressing End on page load (or using "Jump To Bottom" feature of [RGH](https://github.com/sindresorhus/refined-github))

That's not strictly equivalent since it also highlights the actual comment in blue.

**Comment by notlmn** [comment]
> We can use `last_read_at` timestamp of [api.github.com/notifications?per_page=100](https://api.github.com/notifications?per_page=100) to figure out which events/comments are still unread (`created_at` field). Then construct the URL with `#issuecomment-COMMENT_ID` or `#event-EVENT_ID`.

Yeah, but that means we will still be making two new requests for each notification we show, making the user wait for those requests to finish, then show notification.

I think that it might complicate the extension more, but again it's still a useful thing to have.

I'll open the issue again so that anyone can work on it and have a PoC, PRs are always welcome.

**Comment by RomanKornev** [comment]
I might look into this. Any idea where to start looking?

**Comment by notlmn** [comment]
The file and function you are looking for is https://github.com/sindresorhus/notifier-for-github/blob/738ffbabd5d4bffd8ed22985adb6ec55a57303a5/source/lib/notifications-service.js#L13

**Comment by RomanKornev** [comment]
I looked into it a bit more:

If `last_read_at` is `null` we just return the issue URL. Otherwise:
### If it's an issue:
- Use https://api.github.com/repos/:owner/:repo/issues/:number/comments (use `html_url`) and https://api.github.com/repos/:owner/:repo/issues/:number/events (construct `#event` from `id`) to get comments and events and return whichever is first unread.
### If it's a PR:
- We need an additional request for review discussion https://api.github.com/repos/:owner/:repo/pulls/:number/comments and use `html_url` of that comment.

There might be some small stuff left like `#ref-commit` and `#ref-issue` which I don't think is a good idea to request. If nothing is found, just return the issue URL.


Did I miss anything crucial besides `comments`, `events` and `review discussion`? It's totally impractical to request every small detail about a thread. Or is 0-3 additional requests per notification too much already?

**Comment by notlmn** [comment]
What you could also use is the `since` query field accepted by `comments` API ([example](https://api.github.com/repos/sindresorhus/notifier-for-github/issues/169/comments?since=2019-02-09T13:45:22Z)), requesting the API with one second added to the `last_read_at` value and sending it in the `since` field, then you could use the URL of the first result as the last unread notification.

---------------------------

> It's totally impractical to request every small detail about a thread

Agree.

---------------------------

> Or is 0-3 additional requests per notification too much already?

Should ideally be just 1 for each notification, or 2 for any edge cases, and 0 for the null valued notifications.

**Comment by MuntashirAkon** [comment]
Currently, I'm using a modified version of this extension where I've added `#partial-timeline` at the end of URL to jump to the (nearly) last or newest comment. I've found out that the only hassle free way is to add either `#partial-timeline` or `#new_comment_field` at the end of the URL. But the latter one seems to highlight the comment field. So, I went with the former one.

**Comment by notlmn** [comment]
@MuntashirAkon that's one way of handling it, but the newest comment would not always be the last comment in the thread. Like with review comments, and their replies, which are located somewhere in between, so we couldn't use that as a solution.

Yes, at least jumping to the last comment in the thread using your solution is fair enough. Will have a look at this today, and see what I can spin up.
