### ISSUE TITLE
Can display the notification text when the mouse rolls over the expansion icon?

### ISSUE THREAD

**Issue by maliming** [sindresorhus/notifier-for-github#172]
Similar to the following. 

This allows us to preview it before we open the page. This is very useful.

![image](https://user-images.githubusercontent.com/6908465/53238559-7bd47a80-36d4-11e9-923c-aa2f36eb3e35.png)

**Comment by notlmn** [comment]
Title texts are usually useless as mentioned [here](https://mrwweb.com/the-title-attribute-and-why-its-almost-useless/), and [here](https://silktide.com/blog/2013/i-thought-title-text-improved-accessibility-i-was-wrong), and other recent post I can't find.

They are intrusive, cannot be customized or control how the notifications are displayed, how many of them being displayed.

For these reasons, IMHO, opening the notifications page is way better than struggling to make sense of what the inteuaive title popup text contains.

If you think otherwise, and have any better usecase, feel free to reopen the issue.
