### ISSUE TITLE
opening browser notifications for pull requests

### ISSUE THREAD

**Issue by Om4ar** [sindresorhus/notifier-for-github#185]
hey there is a problem when opening a pull request notification (browser notification) it redirect me to `https://github.com/org/repo/pulls/1757`

and that doesn't open the pull request for me 

it should be `https://github.com/org/repo/pull/1757` removing the `s` from `pulls`

**Comment by TheSharpieOne** [comment]
This happens if anything related to querying the API fails. It tries to extract the URL to issue/PR from the API url, but the API URL uses `pulls` and the UI URL is `pull`. Maybe it should `url.pathname.replace('/pulls', '/pull')`?

https://github.com/sindresorhus/notifier-for-github/blob/f8fd946ef8d3bd9634a8cf52e1ef2a7d166ea2f0/source/lib/notifications-service.js#L46-L52

**Comment by notlmn** [comment]
Nice catch @TheSharpieOne, that's really one thing to miss with difference between `user/repo/issues/id` and `user/repo/pull/id`.

PRs welcome to fix this.

Maybe we should also add tests for API handlers in the future.
