### ISSUE TITLE
feature: allow filtering for organization

### ISSUE THREAD

**Issue by NoNameProvided** [sindresorhus/notifier-for-github#190]
It would be cool if users could set a list of organizations to receive the notifications from. When this list is set the extension should show the count only for those organizations specified.

#### Reasoning

I am using multiple browser profiles for my work and personal use and in my work profile, I am only concerned about the notification in specific organizations related to my work.

**Comment by notlmn** [comment]
This has been on my backlog for so long, but I couldn't get the time to properly write and open an issue for this, or to try if this can be implemented. Thanks for starting the discussion.

My idea was to display a list of repos with checkboxes beside them so that you can select to receive notifications from only those repositories.

But I never had the idea of grouping them based on the organization they live in.

This should look something like this:

![image](https://user-images.githubusercontent.com/37769974/62831325-c920b600-bc3a-11e9-8ae5-72e0e96e3342.png)

But by default (with a token that has only `notifications` permission and not `repos` permission) we have access to only public repositories that the user has access to, this includes the users repos and any repos that the user has been invited to collaborate on. But not any repos across organization, public or private require the `repo` permission. That's something to note on.

I really don't have time to do this _right now_, but I'd like to see someone take a stab at it.

**Comment by NoNameProvided** [comment]
Thanks for the quick response! 

> My idea was to display a list of repos with checkboxes beside them so that you can select to receive notifications from only those repositories.

I am not sure how this can be done, I mean what repositories to show there? There are millions of (public) repositories and how can the extension decide which ones to show?  

For this reason, I would go for an input instead where the user can enter the name of the organization they want to filter to. Maybe we can show checkboxes for the repositories in those organizations if needed but I would go for organizations only in the first iteration. (I also think filtering for a few specific repositories is quite an exotic use-case I mean I cannot think a reason to follow a few repos only.)

> I really don't have time to do this right now, but I'd like to see someone take a stab at it.

No promises but probably I will take a shoot at this. 

Do you have any technical advice on how to approach the issue? My first idea would be to still load all the notifications and filter them in the extension based on the preferences. I don't see any repo/org related filtering options for the notifications besides loading notifications for specific repositories but multiple requests would just complicate things more than necessary IMO.

**Comment by notlmn** [comment]
> There are millions of (public) repositories and how can the extension decide which ones to show?

We won't be loading every repo that GitHub hosts, only the repos the current user has access to. This is done by pinging the `https://api.github.com/user/repos` endpoint with the users token, then we get a list of repos that the user has access to.

Each repo has a name and a login name which is essentially the organization it lives in. This result is to be cached maybe for a day instead if pinging the API every time the options UI is opened.

Ideally there would also be a search input so that the user can search for their repositories (only the cache, not entire GitHub), I'm still thinking how that could be implemented.

-----------------------

> My first idea would be to still load all the notifications and filter them in the extension based on the preferences. I don't see any repo/org related filtering options for the notifications besides loading notifications for specific repositories but multiple requests would just complicate things more than necessary IMO.

Yup, making multiple requests one for each repo/org is not ideal. We'll have to load all the notifications and filter them on the client side and show only those needed.

I really hope GitHub soon builds a GraphQL endpoint for notifications, so that all of these could be easily solved.

-------------------

> No promises but probably I will take a shoot at this.

No problem, I'll probably end up implementing it myself at some point but not at the moment.

**Comment by jroehl** [comment]
Hi, as I would love to have that feature - I'd be willing to work on that!

**Comment by notlmn** [comment]
@jroehl, by all means go for it. I end up working on feature requests myself but that usually takes a lot of time.

You can ping me for any pointers.

**Comment by jroehl** [comment]
Great! I already started to work on it - currently stumbled upon an issue with the [webext-options-sync](https://github.com/fregante/webext-options-sync) package. 

The size of the keys in sync storage is quite limited and therefore the data should be compressed before storing it.

I already created a [PR](https://github.com/fregante/webext-options-sync/pull/40) for this - will see how that goes and keep you posted.

**Comment by fregante** [comment]
> keys in sync storage is quite limited

The limit is 5MB. Does this feature take more than 5MB of storage? If so: https://github.com/sindresorhus/notifier-for-github/pull/192#issuecomment-547529642

**Comment by jroehl** [comment]
> > keys in sync storage is quite limited
> 
> The limit is 5MB. Does this feature take more than 5MB of storage? If so: [#192 (comment)](https://github.com/sindresorhus/notifier-for-github/pull/192#issuecomment-547529642)

The limit for local storage (not sync storage) seems to be 5MB - per key, it's much less according to [sync storage properties](https://developer.chrome.com/apps/storage#properties). Or am I mistaken. The error I received was `QUOTA_BYTES_PER_ITEM`, which points to per-key storage limitations.
