### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by PalashBansal** [sindresorhus/notifier-for-github#197]
I just installed this extension but not able to use.
It shows below icon-
![image](https://user-images.githubusercontent.com/6822117/67757159-49e49680-fa61-11e9-8d96-d61befef11aa.png)
I configured with github token as well. I restarted my chrome browser too.
It just shows "Unnknow error" on hovering mouse cursor.
Please help. Or, let me know if this portal is not the correct way to raise these type of issues.
Also, please update error message to something relevant(instead of "Unknown error") iff possible.

Please feel free to get back to me in case of any further info. required for debugging the root cause.

**Comment by WaleedAshraf** [comment]
Same issue.

**Comment by PalashBansal** [comment]
Seems like the community is not currently active on this extension(last commit 3months ago). Uninstalled the extension. But I would still like to have it on my chrome ONCE fixed(I get any reply from community on how to get it fixed), or will look for the exact root cause myself sometime, or alternative extension.

**Comment by notlmn** [comment]
Sorry for not getting on this faster, I haven't been able to be active on GitHub lately.

The "unknown error" issue you see might be because of a variety of reasons that might go wrong (like permissions and networking requests being blocked).

One thing you can help me with to debug this thing is go into the settings view for the extension and click on the "background page" under "inspect views" section to open devtools for the extension and see if you have any errors there.

The last publish for this extension was in August, which up-to this point hasn't had any issues, make sure you are on the latest release (`19.8.4.814`).

**Comment by notlmn** [comment]
> Seems like the community is not currently active on this extension(last commit 3months ago).

Yes, because the extension currently is in maintenance mode and any new feature requests are handled by mostly just me, who haven't been active lately. I want you to understand that people have their own lives to deal with other than the issues they get on GitHub.

**Comment by PalashBansal** [comment]
@notlmn Thanks for your response, I hope you are doing good.
I added the extension again and it seems to be working. However, if issue arises again, i will report back the same after following the steps mentioned by you above.
@WaleedAshraf As you are seeing the issue lately, it would be good if you can provide the required detailed error info.

**Comment by WaleedAshraf** [comment]
@PalashBansal Okay, I'll keep an eye on it when it fails again. 👍 
@notlmn thanks for the response.

**Comment by notlmn** [comment]
Feel free to open the issue if you run into any similar issues
