### ISSUE TITLE
API token is lost on all devices when signing into Firefox on a new device

### ISSUE THREAD

**Issue by adueppen** [sindresorhus/notifier-for-github#201]
The extension will normally work fine, but as soon as I sign into Firefox on a new device, all other devices that I have signed in will lose the entered token. It looks as though Firefox is installing the extension and then syncing the default lack of a token with all other devices.

**Comment by notlmn** [comment]
Sorry for the late reply.

We do not perform any sync operation immediately after the extension is installed, we get options from "online store", which should generally be populated by Firefox.

Maybe you are in a situation trying to set new options before the options even had a chance to sync, can you confirm this behavior is still happening. (Try waiting for a sec after the extension is installed for the options to sync).

**Comment by fregante** [comment]
There's a chance that this was due to a race condition in webext-options-sync up to 1.2.0: https://github.com/fregante/webext-options-sync/issues/38

notifier-for-github was using v1.1.0 until March 21 ([first commit](3b1e000c959f103f267961d773657185993eddcb) in months)

I think this is automatically resolved now since there's no package lock
