### ISSUE TITLE
Apply filter to notification count too

### ISSUE THREAD

**Issue by LukasKalbertodt** [sindresorhus/notifier-for-github#225]
Currently the configurable filter only applies to desktop notifications. But it would be great if it also applies to the notification count. I often have desktop notifications completely disabled and regularly look at the top right to see the notification count. But at work, I only want to see the count for all work related notifications.

It would be extra awesome if clicking the icon would then link to the notification page with appropriate filters applied! E.g. `https://github.com/notifications?query=repo%3Asindresorhus%2Fnotifier-for-github`, but with all repos that have notifications and are selected by the filter. 

<sub>Thanks a lot for this great extension by the way!</sub>

**Comment by notlmn** [comment]
I really like this request but we can not implement this because of GitHub's API restriction.

The UI we see and API GitHub provides are completely different, which for example doesn't include any option for applying filters to notifications (https://docs.github.com/en/rest/reference/activity#list-notifications-for-the-authenticated-user).
