### ISSUE TITLE
Can't reset, click doesn't work

### ISSUE THREAD

**Issue by irvnriir** [sindresorhus/notifier-for-github#229]
i renamed the firefox Profile, and it's folder in Roaming, but didn't do so in `Local\Mozilla`, and deleted the 2nd . reinstalled the extension, but clicking on the icon does nothing . it works in other Profile, but obviously i need to save this one . how can i {reset / completely delete} it, to make it work ?

**Comment by notlmn** [comment]
This is not something we as extension authors are supposed to handle as you are making modifications at the system level.

But what I can suggest you to do though, is to reset Firefox entirely, that might solve it. Don't just take my word for it as it may have some other unintended side effects. Proceed at your own caution.

**Comment by irvnriir** [comment]
@notlmn i just ask for a list of files that store the extension's data.

p.s. supporting the export of userprofile is nothing different than a feature, multiple extensions do such (store all user-data in Roaming, the same as yours, by the way), and all 8 of the other extensions handled the refresh.

**Comment by notlmn** [comment]
> i just ask for a list of files that store the extension's data.
> 
> p.s. supporting the export of userprofile is nothing different than a feature, multiple extensions do such (store all user-data in Roaming, the same as yours, by the way)

That's up to the browser, it can store the data wherever it pleases (and changes widely between browsers). The extension does not have access to your filesystem in any way, all it sees is an API provided by the browser in hope that whatever data is saved can be retrieved using that API.

---------

> and all 8 of the other extensions handled the refresh.

That ranges widely between extensions, we use the `browser.storage.sync` API that allows us to sync extensions settings across browser accounts (usually to have same settings on home and work computer, if you are logged into your browser). This again could've happened for various reasons, mostly because of the browser being unable to sync those settings.

I any case, I suggest you to make sure that you have a token entered in the extension settings view in order for it to work. And if possible share any error logs  and extension version you have installed here to see if this is an issue from our end.

**Comment by irvnriir** [comment]
The entered token persisted trough the refresh.
This is what i have in `"about:debugging#/runtime/this-firefox" \ Inspect` :
![Screenshot 08-04-2020 17 03 34](https://user-images.githubusercontent.com/13949704/89323069-b89bf380-d674-11ea-9d45-a16dae5949e5.png)

Tell if i can use some way to gather more information .

**Comment by notlmn** [comment]
Looks like Firefox fails to create a background page for the extension, because you manually modified profile files on disk.

Sorry but this is still not an issue from our end.

**Comment by irvnriir** [comment]
The extension can't be reinstalled/reset, so it kept broken, if certain data was deleted.
its issue of the extension, stop saying its not . if browser.storage.sync doesn't allow to avoid this, thats other question, but don't say alike changes in the extension wouldn't help .

**Comment by radiovisual** [comment]
@irvnriir  think what @notlmn is trying to say is that is that you are changing your system-level files (for example: renaming your Firefox profile is a system-level change). The unintended consequences of making changes to your browser settings or system changes would be really difficult to support. 

If you can provide step-by-step bug reproduction steps (it is still not 100% clear to me how you got into the state that you did) then maybe we can offer some pointers to help. There is very little we could do to help without more information.

Have you tried putting the Firefox Profile back to its original name/path, and then deleting/reinstalling?

**Comment by notlmn** [comment]
Hey @irvnriir, I couldn't follow up with this issue as I'm in the midst of moving between job roles and having little to no time to debug issues for now. I'll be sure to get back to this whenever possible.

Thanks @radiovisual for following up on this.

**Comment by irvnriir** [comment]
@radiovisual
Its already discussed in specifics .

Already did, long ago .
> i renamed the firefox Profile, and it's folder in Roaming, but didn't do so in `Local\Mozilla`, and deleted the 2nd

**Comment by irvnriir** [comment]
When you rename the profile in Roaming, you may also need to do so in profiles.ini there .

**Comment by notlmn** [comment]
> When you rename the profile in Roaming, you may also need to do so in profiles.ini there .

Could I ask if you've been able to get it working after doing this?

**Comment by irvnriir** [comment]
after this, folder with the new name is created in `Local\Mozilla`, so __probably__ it wouldn't .

**Comment by radiovisual** [comment]
@irvnriir 

> @radiovisual
> Its already discussed in specifics .

I know that you have already provided some details, but I still feel that some clarity is missing. The details from my point of view are still a bit vague, so something more like a step-by-step to help me or others reproduce the issue would be helpful. So far I feel like you are sharing more of an "overview" without specifics. 

So far this is what I feel like we have to go on:

> i renamed the Firefox Profile, and it's folder in Roaming, but didn't do so in Local\Mozilla, and deleted the 2nd

and 

> When you rename the profile in Roaming, you may also need to do so in profiles.ini there .

and 

> after this, folder with the new name is created in Local\Mozilla, so probably it wouldn't .

For me, these steps and details are not clear enough to help unless you just want us to start guessing at what could be the problem. 

Sorry if this is frustrating for you, I would like to try and help, but personally, I need more info to work with.

**Comment by irvnriir** [comment]
@radiovisual
> Its already discussed in specifics .

at all was about the first part of your message .

you can get this issue by just doing your self as written, if there is anything that you do not understand, type the exact thing .

**Comment by radiovisual** [comment]
> you can get this issue by just doing your self as written

No, I can't, which is why I keep asking for more details.

> if there is anything that you do not understand, type the exact thing

1. How many profiles did you have to start with? 1, or more?

2. Where / how did you change your profile? Did you rename it manually? Or did you do it in the browser? Did you use any automated utilities for this? 

3. At what point during the renaming of the Profile did you install/uninstall the extension? Which profile (maybe using terms like "Profile A" and "Profile B" would help with the clarification) was active when you installed? Which profile was active when you uninstalled? The part where the browser extension fits into these steps is the most unclear to me, because it sounds like you are dealing with multiple instances of the extension with only one Profile, but without more information, it is still unclear. 

4. Did you do anything to attempt to manually delete the extension files during this process? Meaning: did you use some process other than [the "official" Firefox way](https://support.mozilla.org/en-US/kb/disable-or-remove-add-ons#w_removing-extensions)?

5. Is your new profile working as expected in all other aspects? Or are any of your other extensions failing?

6. Are your Profiles using some custom location, or are you using default locations? Does any custom file paths have proper read/write permissions?

7. What is your browser version? and Operating System version?

**Comment by irvnriir** [comment]
@radiovisual 
more .
browser/{firefox.exe -p}, no difference .
extension required re-/install after deleting `Local\Mozilla` (all extensions disappeared from taskbar, but the spaces stayed) .
`-`
5. yes . no .
default .
last stable .

**Comment by irvnriir** [comment]
oh, technically 3. : after deleting in `Local\Mozilla` or folder renaming in Roaming ;

**Comment by irvnriir** [comment]
and sync was enabled, you may be missing this

**Comment by notlmn** [comment]
> after this, folder with the new name is created in `Local\Mozilla`, so **probably** it wouldn't .

Have you tried merging files from previous profile directory (that you supposedly didn't delete) into the new directory Firefox automatically created after you edited `profiles.ini`?

If you've deleted your previous profile (in `Local\Mozilla`), then there might be nothing we could do here. In that case the only thing we could suggest you to do is create a fresh profile and start over. And as you mentioned that [you have sync enabled](https://github.com/sindresorhus/notifier-for-github/issues/229#issuecomment-673330051), that shouldn't be a problem.

-------

Also @irvnriir, it doesn't cost you anything to take your time and respond with some specifics that you might've missed to mention or steps you've taken from your end to make this work, in a bit more detail when requested the second time around. We're all here to help each other.

**Comment by irvnriir** [comment]
@notlmn
i deleted it, even if this my profile can't be fixed, you still can prevent the issue from happening again .

the all cause is a 3 or 4 simple steps . unless you want me to list the state of every single setting on the PC, its no more info that can be added . if i think that some info can be related, i add it, if you think that something else can be, mention it .

**Comment by notlmn** [comment]
> i deleted it, even if this my profile can't be fixed, you still can prevent the issue from happening again .

Oh how do you propose we hande a system level change, eg: renaming files, or launching a video game, or a kernel exception.

**Comment by irvnriir** [comment]
@notlmn
wth .. . at least reinstall have to handle this .
and yes, reinstall of the extension, not the Profile or Firefox .

**Comment by irvnriir** [comment]
if the issue is caused by function which's use you can't avoid without loosing some feature, then the question is : do you think it worth loosing the feature ;, the chance that the issue can't be fixed within the extension development is near 0 .

**Comment by notlmn** [comment]
Maybe you could try running `browser.storage.sync.clear()` and `browser.storage.local.clear()` in the extensions background devtools, then disable/enable or uninstall/install the extension again. Provide logs if needed, also the version of extension you have installed and any other information you'd like to share.

**Comment by radiovisual** [comment]
> wth .. . at least reinstall have to handle this .
and yes, reinstall of the extension, not the Profile or Firefox .

I think the extension does provide all the functionality required for uninstall/reinstall. I can freely uninstall and reinstall the extension without problems. @irvnriir you started running into problems after you started making custom changes to your browser. This is not something I have ever seen an extension author try to support before. This is a complex (and likely very rare) edge case. We are trying to help as best we can, but I still don't see this being something that can get fixed through the extension's code. Unless you disagree, maybe you can provide a Pull Request with your proposed fix in mind, or some ideas at what _you think_ the problem is, because at this point, we are mostly just guessing at different things that might help. We are trying to help as best we can.

**Comment by radiovisual** [comment]
> wth .. . at least reinstall have to handle this .
> and yes, reinstall of the extension, not the Profile or Firefox .

I think the extension does provide all the functionality required for uninstall/reinstall. I can freely uninstall and reinstall the extension without problems. @irvnriir you started running into problems after you started making custom changes to your browser. This is not something I have ever seen an extension author try to support before. We are trying to help as best we can, but I still don't see this being something that can get fixed through the extension's code. Unless you disagree, maybe you can provide a Pull Request with your proposed fix in mind, or some ideas at what _you think_ the problem is, because at this point, we are mostly just guessing at different things that might help. We are trying to help as best we can...

And just as it would be with any problem: if we can't reproduce the problem, it becomes really difficult (or impossible) to find a proper solution. @irvnriir you have repeated multiple times that you have shared all you can, and that the reproduction steps are simple, but maybe our endless stream of questions is a clue that we _don't_ have all the info we need to reproduce the problem (or even fully understand what exactly happened to get into this state). There is nothing simple about this (in my opinion), so it might help if you stop treating this as a simple and clearly-stated problem and just let the discussion flow organically without accusations, expectations or assumptions. We are trying to help, so we need to discuss without going around in circles.

**Comment by irvnriir** [comment]
@notlmn . the `browser.storage.sync.clear()` completely fixed the issue ! (no other actions was needed)

@radiovisual
managing userfiles on windows, in bypass of the target program, never was rare . all the other involved extensions worked fine with this .

if the simple steps which is all unusual that happened since it worked, and which i have listed, doesn't reproduce the issue, repeating "magic cast the list of true reasons and send it" won't help, i've answered every specific info request that you've send so far .

#
i also reproduced it with a testing profile (the both was initially created with older version of firefox), but then created a new one and couldn't reproduce the issue with it .

**Comment by notlmn** [comment]
> and couldn't reproduce the issue with it .

That's how software works
