### ISSUE TITLE
Microsoft Edge version from different author

### ISSUE THREAD

**Issue by muuvmuuv** [sindresorhus/notifier-for-github#256]
Hey I just wanted to ask if this MS Edge version is legit or a just a test/fork? Would like to use it but don't know if it will receive future updates.

I think its form @notlmn 

https://microsoftedge.microsoft.com/addons/detail/notifier-for-github/ipnhpapgpnoadggfoepbedokgppcodkl

**Comment by notlmn** [comment]
Hey Marvin, yup, I do [maintain](https://github.com/sindresorhus/notifier-for-github#maintainers) (albeit, inactive) this extension.

After talking to Sindre, I initially published the MS Edge version of the extension, along with some updates down the road. But that hasn't received much love in terms of maintenance as there is simply no API to deploy to Edge Store using continuous deployment, we'd have to manually deploy upload a zip every time.

I just built this one locally and uploaded to the Edge store as `21.4.6.940`. As that takes manual review, expect that to reach you in a few days. I'll try to post here when that is done, or if I push any other newer releases there.

But for now, that version is under "best-effort" support basis, as we don't exactly support Edge addons (mostly because of the lack of automation).

**Comment by muuvmuuv** [comment]
Wasn't aware that automation is completely missing in Edge Store, what a shame. Thanks for clearing things up and your time to maintain that.

**Comment by notlmn** [comment]
I've unpublished the Edge addon due to difficulty in maintaining it.

The version published on Chrome Web Store should can be installed for users of Edge.
