### ISSUE TITLE
Supporting custom notification sound

### ISSUE THREAD

**Issue by scarf005** [sindresorhus/notifier-for-github#280]
hello, thank you for creating this app!
I was wondering, could it be possible to select local audio file for custom notification sound?

**Comment by notlmn** [comment]
I like the idea but that would be a too much of a hassle to build and maintain.

The extension is supposed to be minimal and basic :)

**Comment by scarf005** [comment]
i see. i guess i could build it locally, should i just run `npm build`?

**Comment by scarf005** [comment]
hmm, so i'm getting some problems while locally building:

```ts
> @ build /home/scarf/repo/etc/notifier-for-github
> parcel build source/manifest.json --dist-dir distribution --no-cache --no-content-hash --no-source-maps --no-optimize --no-scope-hoist --detailed-report 0

🚨 Build failed.

@parcel/transformer-webextension: Invalid Web Extension manifest

  /home/scarf/repo/etc/notifier-for-github/source/manifest.json:36:3
    35 |     "page": "options.html",
  > 36 |     "chrome_style": true
  >    |     ^^^^^^^^^^^^^^ Did you mean "browser\_style"?
    37 |   },
    38 |   "web_accessible_resources": [

 ELIFECYCLE  Command failed with exit code 1.
```
i'm not sure where should i change.

**Comment by notlmn** [comment]
Due to updates in our dependencies, you have to install the exact versions listed in npm package-lock.json. I might update the dependencies in the future when I get to it, for now, it "just works" and I intend to keep it that way.

On the other side, this is not a support channel, you should try searching on the web and lookup resources on browser extensions.
