### ISSUE TITLE
White icon for dark themes

### ISSUE THREAD

**Issue by Crayder** [sindresorhus/notifier-for-github#85]
My previous extension seems to be removed from the face of Earth, and it was the only one on the web store that I could see in my dark theme. Your extension looks promising though and I hope you can consider the option of a white icon.

In case your wondering what it looked like:
![image](https://cloud.githubusercontent.com/assets/9919010/15739540/799c786a-287e-11e6-8119-e8d9c9d2222b.png)

**Comment by techtonik** [comment]
Where is the counter/notifier there?

**Comment by Crayder** [comment]
Well, obviously I didn't have any notifications at the time I took that screenshot.

But it's a red counter, and I like that color too since it matches the official google counters.

**Comment by Crayder** [comment]
Nevermind, just got a notification!

![image](https://cloud.githubusercontent.com/assets/9919010/15773690/59fee0ba-2946-11e6-8e40-89fe2715c6e9.png)

**Comment by techtonik** [comment]
So, what is the problem with whitecat with that icon?

**Comment by Crayder** [comment]
There's nothing wrong with it. I just like the classic white circle.

For the moment I can compile my own version with my own icon, but still aside.

**Comment by sindresorhus** [comment]
Didn't even know Chrome supported themes. Sorry, but not interested in having an option for such a narrow use-case.

**Comment by techtonik** [comment]
I am also against featurecreep as it turns maintenance into a nightmare. From the other side it is good that you at least had not spent time writing and testing the patch. =)

**Comment by whoiskevinrich** [comment]
Not a great look.

![image](https://user-images.githubusercontent.com/2496620/48513202-15f07100-e810-11e8-82fd-36d6cab5e3ed.png)

**Comment by notlmn** [comment]
Never knew that this issue existed. Dark mode is an interesting use case but hard to implement.

I'm not sure if the implementation is easy, or if we require a different icon for all possible themes out there.

Anyway I'll open the issue again, and see if anyone grabs it and finds an interesting solution (for only two icons, not more).

**Comment by Crayder** [comment]
Finally, perhaps I'll add this extension back 👍

**Comment by notlmn** [comment]
Fixed in https://github.com/sindresorhus/notifier-for-github/commit/212a51bc5e7a15ab35d4fccbf3d414eceadbe551.

It should look like the one below.

![image](https://user-images.githubusercontent.com/37769974/48776648-742cc080-ecf6-11e8-9abc-9473dab1c94d.png)

-----

Detecting theme and adding a different icon would be hard to implement (I don't know if there is a way to detect theme), and very hard to maintain. So I settled with adding complementary background/border to the existing icons.

Hope you are satisfied with it, or open another issue for further discussion!

**Comment by ArnaudLigny** [comment]
Hello @notlmn, are you sure it's not a case of non-respect of usage rules of The GitHub logo? :-/

(ref: https://github.com/logos)

**Comment by notlmn** [comment]
The issue was already looked up at a long time ago by @sindresorhus in https://github.com/sindresorhus/notifier-for-github/commit/dcc53e06f6ed577a752c6f9efafeabf234c315c9.

------------

But to revise, there are three icons used by the extension

- A generic bell icon ([this](https://github.com/sindresorhus/notifier-for-github/blob/212a51bc5e7a15ab35d4fccbf3d414eceadbe551/source/icon.png))
  Used as the __actual extension icon__ (see below)
- Two GitHub icons
  - One used as the __toolbar__ icon ([this](https://github.com/sindresorhus/notifier-for-github/blob/212a51bc5e7a15ab35d4fccbf3d414eceadbe551/source/icon-toolbar.png))
  - And the other as icon for __notifications__ ([this](https://github.com/sindresorhus/notifier-for-github/blob/212a51bc5e7a15ab35d4fccbf3d414eceadbe551/source/icon-notif.png))

----------------

This is what the extensions icon looks like
- On Chrome Web store
  ![image](https://user-images.githubusercontent.com/37769974/48780026-e6090800-ecfe-11e8-97ff-339ca968e6fa.png)
- And in the extension page
  ![image](https://user-images.githubusercontent.com/37769974/48780065-ff11b900-ecfe-11e8-846f-ff24da512869.png)

--------------

I actually concerned with this, removed also changed the toolbar icon to bell in #151. But for some reason @sindresorhus added it back in https://github.com/sindresorhus/notifier-for-github/commit/67f9912a97aec1380d74497c776d2c2fb2869ed3.

-------------

So according to my understanding (correct me if I'm wrong) and Sindre's (because of the change, I presume), we are not using GitHub's icon as an icon for this application, and therefore not violating their rules (again, I might be wrong).

I'm not a lawyer and do not have any in-depth understanding of this stuff. If anyone who has more understanding of this can help me and this our out to make resolve any issues, I would be very happy to accept your help.

--------------

And @Narno, I understand your concern, and is very valid, and hope I made a good job at explaining things. And if there are any other issues try opening a new one instead of discussing it here.

Peace 🖖!

**Comment by sindresorhus** [comment]
Yes, GitHub is fine with us using it for the toolbar icon.

**Comment by whoiskevinrich** [comment]
Looks great! Thank you.

**Comment by techtonik** [comment]
![image](https://user-images.githubusercontent.com/515889/48826784-67eb4680-ed7c-11e8-9128-fefd10216d01.png) - what about this? =) Did you use some broken AI to paint it?
